import NavigationBar from "../components/navigationbar.js";
import Footer from "../components/footer.js";
import "./globals.css";

export const metadata = {
	title: "nextjs-starting-app",
	description:
		"Generated by create next app - For Final ProjectComparisonsNext.js",
};

export default function RootLayout({ children }) {
	return (
		<html>
			{}
			<head />
			<body className="flex flex-col h-screen">
				<NavigationBar />
				<div className="flex-grow">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
